### ISSUE TITLE
Requisiti

### ISSUE THREAD

**Issue by rossoc** [Sdraiati/docs#3]
Individuazione dei requisiti a partire dai casi d'uso. Questa issue, potrebbe essere svolta anche faccia a faccia tra di noi

**Comment by simocare** [comment]
Requisiti:
1. tutte le pagine html stabilite;
2. css completo;
3. database;
4. backend;
5. login;
6. line chart;
7. cake chart;
8. import/export #5
--- progetto consegnabile ---
9. categorie #3 e #2
10. paperone :) o :(
11. obbiettivi da raggiungere (milestone)
